### ISSUE TITLE
RPC Issues

### ISSUE THREAD

**Issue by TrevorJTClarke** [Cron-Near/croncat#17]
agent is exiting after RPC failure
  - TypeError cannot read property "status" of undefined actions.js 231:52
- User submitted: try/catch in actions.js 224, getCronManager where accountId is null

**Comment by t-ilk** [comment]
Hey,

I think this issue is caused by the system leaving `accountId` parameter unset on certain conditions. I am going to unfold this a little, but first as a **TLDR:**

My claim is that changing `this.accountId = null` to `this.accountId = config.accountId || null` will solve this error.



It is possible that `getAgent` in this part of the function `runAgentTick` can be called before `accountId` parameter was set in the near provider:

``` js 
try {
    agentSettings = await getAgent(agentId)
  } catch (ae) {
    agentSettings = {}
  }
```

Although a default `accountId` parameter is given where an instance of this class is being generated:
```js
export const Near = new NearProvider({
  networkId: env === 'production' ? 'mainnet' : 'testnet',
  accountId: AGENT_ACCOUNT_ID,
})
```


This value is initialized as `null` in `NearProvider`:
```js
  constructor(config = {}) {
    ...
    ...
    ...
    this.accountId = null

    return this
  }
```

And if a situation where `getAgent` is called before any method that sets `accountId` parameter for near provider, this could happen:

1.   `getAgent` is called inside `runAgentTick`,
2.  `getCronManager(null, options)` is called,
3. If there is no `cronManager` instance, it will attempt to create a new one,
4. It will set the `accountId` parameter of the new provider to given value in function arguments (in this case, since we provided `null`, it will skip this assignment),
5.  `getContractInstance` inside the new provider is called,
6.  `loadAccount` is called inside `getContractInstance`,
7.  `loadAccount` attempts to fetch a user with the specified `accountId`, and since none was provided, it will fail,

And after this we will follow the calls back upwards:
8.  `manager.get_agent` inside `getAgent` fails, and either resolves to `undefined`, or remains as an unresolved promise,
9.  `agentSettings` in ln. 225 remains unset,
10.  `if` check in ln. 236 fails at `!agentSettings` part,
11. System attempts to reach `agentSettings.status`, but `agentSettings` is `undefined`, and this results in an error.

So, here is my case. Hope this will help you solve the issue.
